import _ from 'lodash';

let mapDeepValue;

/**
 * Recursively creates an object with the same keys as object and values
 * generated by running each own enumerable property of object
 * through iteratee. The iteratee function is bound to thisArg
 * and invoked with three arguments: (value, key, object).
 *
 * @see https://lodash.com/docs#mapValues
 */
mapDeepValue = (source: Object, callback: Object, propertyPath: Array<string> = []): Object => {
    return _.mapValues(source, (value, key) => {
        let path;

        path = propertyPath.concat([key]);

        if (_.isObject(value)) {
            return mapDeepValue(value, callback, path);
        } else {
            return callback(value, key, path);
        }
    });
};

export default mapDeepValue;
